# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleverTapDemo' do

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

pod 'CleverTap-iOS-SDK'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 
            'CLEVERTAP_HOST_WATCHOS=1']
        end
   end
end
